import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../common/components/layout/Layout';
import BaseballScoreboard from '../common/components/BaseballScoreboard';
import { getSession, useSession } from 'next-auth/react';
import { CtxOrReq } from 'next-auth/client/_utils'; 
import { useCallback, useEffect, useState } from 'react';
import LinkList from '../common/components/LinkList';

const Home: NextPage = () => {
    const { data: sessionData } = useSession();
    return (
        <>
            <Head>
                <title>Salesforce JS Demo</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <LinkList />
            </Layout>
        </>
    );
};

export const getServerSideProps = async (ctx: CtxOrReq | undefined) => {
    const session = await getSession(ctx);
    /**
     * If session is available then redirect to main page.
     */
    if (!session) {
        return {
            redirect: { destination: '/signin', permanent: false },
        };
    }

    /**
     * Return providers and CSRF Token
     */
    return {
        props: { session },
    };
};

export default Home;
